import { expect, test } from '@playwright/test'
import { accounts } from '../fixtures/auth'

const organizationBase = '/org/org_school-default'

test.describe('Human UX navigation foundation @smoke @compact', () => {
  test('desktop opens the grouped navigation and fully hides it after collapse', async ({ browser }) => {
    const context = await browser.newContext({ storageState: accounts.teacher.storageState })
    await context.addInitScript(() => {
      for (const key of Object.keys(localStorage)) if (key.startsWith('sidebarNavigation:')) localStorage.removeItem(key)
    })
    const page = await context.newPage()
    await page.goto(`${organizationBase}/overview`)
    const navigation = page.getByRole('navigation', { name: '教师主导航' })
    await expect(navigation).toBeVisible()
    await expect(page.locator('[data-navigation-mode="expanded"]')).toBeVisible()
    for (const group of ['教学', '学生与团队', '学校', '社区']) await expect(navigation.getByText(group, { exact: true })).toBeVisible()
    await expect(navigation.getByRole('link', { name: '首页' })).toHaveAttribute('aria-current', 'page')
    await expect(navigation.getByRole('link', { name: '评测记录' })).toBeVisible()
    await page.getByRole('button', { name: '收起导航' }).first().click()
    await expect(page.locator('[data-navigation-mode="collapsed"]')).toBeVisible()
    await expect(navigation).toBeHidden()
    await expect(page.getByRole('button', { name: '显示导航' })).toBeVisible()
    await expect(page.locator('header img[alt="Carits"]')).toBeVisible()
    await page.reload()
    await expect(page.locator('[data-navigation-mode="collapsed"]')).toBeVisible()
    await expect(navigation).toBeHidden()
    await context.close()
  })

  test('navigation has only persistent-sidebar and drawer responsive modes', async ({ browser }) => {
    const viewports = [
      { width: 1100, height: 800, mode: 'expanded', persistent: true },
      { width: 1099, height: 800, mode: 'closed', persistent: false },
      { width: 1024, height: 768, mode: 'closed', persistent: false },
      { width: 800, height: 900, mode: 'closed', persistent: false },
      { width: 390, height: 844, mode: 'closed', persistent: false },
    ] as const
    for (const viewport of viewports) {
      const context = await browser.newContext({ storageState: accounts.teacher.storageState, viewport })
      await context.addInitScript(() => {
        for (const key of Object.keys(localStorage)) if (key.startsWith('sidebarNavigation:')) localStorage.removeItem(key)
      })
      const page = await context.newPage()
      await page.goto(`${organizationBase}/overview`)
      const shell = page.locator('[data-navigation-mode]')
      const navigation = page.getByRole('navigation', { name: '教师主导航' })
      await expect(shell).toHaveAttribute('data-navigation-mode', viewport.mode)
      if (viewport.persistent) {
        await expect(navigation).toBeVisible()
      } else {
        await expect(navigation).toBeHidden()
        await page.getByRole('button', { name: '显示导航' }).click()
        await expect(shell).toHaveAttribute('data-navigation-mode', 'drawer')
        await expect(navigation).toBeVisible()
        const box = await page.locator('#app-sidebar').boundingBox()
        expect(box?.width).toBe(232)
        await expect(page.locator('#app-sidebar').getByRole('button', { name: '关闭导航' })).toBeFocused()
        await expect(page.locator('body')).toHaveCSS('overflow', 'hidden')
        const drawerLogos = await page.locator('img[alt="Carits"]').evaluateAll(images => images.filter(image => {
          const style = getComputedStyle(image)
          const rect = image.getBoundingClientRect()
          return style.visibility !== 'hidden' && style.display !== 'none' && rect.width > 0 && rect.height > 0
        }).length)
        expect(drawerLogos).toBe(1)
        await page.keyboard.press('Escape')
        await expect(shell).toHaveAttribute('data-navigation-mode', 'closed')
        await expect(page.getByRole('button', { name: '显示导航' })).toBeFocused()
      }
      const visibleLogos = await page.locator('img[alt="Carits"]').evaluateAll(images => images.filter(image => {
        const style = getComputedStyle(image)
        const rect = image.getBoundingClientRect()
        return style.visibility !== 'hidden' && style.display !== 'none' && rect.width > 0 && rect.height > 0
      }).length)
      expect(visibleLogos).toBe(1)
      expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
      await context.close()
    }
    const preferenceContext = await browser.newContext({ storageState: accounts.teacher.storageState, viewport: { width: 1100, height: 800 } })
    await preferenceContext.addInitScript(() => {
      for (const key of Object.keys(localStorage)) if (key.startsWith('sidebarNavigation:')) localStorage.removeItem(key)
    })
    const preferencePage = await preferenceContext.newPage()
    await preferencePage.goto(`${organizationBase}/overview`)
    const preferenceShell = preferencePage.locator('[data-navigation-mode]')
    await expect(preferenceShell).toHaveAttribute('data-navigation-mode', 'expanded')
    await preferencePage.setViewportSize({ width: 800, height: 900 })
    await expect(preferenceShell).toHaveAttribute('data-navigation-mode', 'closed')
    await preferencePage.getByRole('button', { name: '显示导航' }).click()
    await expect(preferenceShell).toHaveAttribute('data-navigation-mode', 'drawer')
    await preferencePage.locator('[data-navigation-backdrop]').click({ position: { x: 400, y: 100 } })
    await expect(preferenceShell).toHaveAttribute('data-navigation-mode', 'closed')
    await preferencePage.getByRole('button', { name: '显示导航' }).click()
    await preferencePage.reload()
    await expect(preferenceShell).toHaveAttribute('data-navigation-mode', 'closed')
    await preferencePage.setViewportSize({ width: 1100, height: 800 })
    await expect(preferenceShell).toHaveAttribute('data-navigation-mode', 'expanded')
    await preferenceContext.close()
  })

  test('header anchors stay fixed while the same organization shell survives module changes', async ({ browser }) => {
    const context = await browser.newContext({ storageState: accounts.teacher.storageState, viewport: { width: 1440, height: 900 } })
    const page = await context.newPage()
    await page.goto(`${organizationBase}/overview`)
    const shell = page.locator('[data-navigation-mode]')
    await expect(shell).toHaveAttribute('data-navigation-mode', 'expanded')
    await shell.evaluate(element => { element.setAttribute('data-test-instance', 'original-shell') })
    const trigger = page.getByRole('button', { name: /切换工作区，当前/ })
    const original = await trigger.boundingBox()
    await page.getByRole('button', { name: '收起导航', exact: true }).click()
    await expect(shell).toHaveAttribute('data-navigation-mode', 'collapsed')
    const collapsed = await trigger.boundingBox()
    expect(Math.abs((original?.x || 0) - (collapsed?.x || 0))).toBeLessThanOrEqual(1)
    expect(Math.abs((original?.y || 0) - (collapsed?.y || 0))).toBeLessThanOrEqual(1)
    await page.getByRole('button', { name: '显示导航', exact: true }).click()
    const navigation = page.getByRole('navigation', { name: '教师主导航' })
    await navigation.getByRole('link', { name: '训练', exact: true }).click()
    await expect(page).toHaveURL(`${organizationBase}/training-sessions`)
    await expect(shell).toHaveAttribute('data-test-instance', 'original-shell')
    await navigation.getByRole('link', { name: '首页', exact: true }).click()
    await expect(page).toHaveURL(`${organizationBase}/overview`)
    await expect(shell).toHaveAttribute('data-test-instance', 'original-shell')
    await context.close()
  })

  test('a collapsed desktop preference is correct before hydration', async ({ browser }) => {
    const context = await browser.newContext({ storageState: accounts.teacher.storageState, viewport: { width: 1440, height: 900 } })
    const page = await context.newPage()
    await page.goto(`${organizationBase}/overview`)
    await page.getByRole('button', { name: '收起导航', exact: true }).click()
    await expect(page.locator('[data-navigation-mode]')).toHaveAttribute('data-navigation-mode', 'collapsed')
    const serverOnly = await browser.newContext({ storageState: await context.storageState(), javaScriptEnabled: false, viewport: { width: 1440, height: 900 } })
    const serverPage = await serverOnly.newPage()
    await serverPage.goto(`${organizationBase}/overview`)
    await expect(serverPage.locator('[data-desktop-sidebar]')).toHaveAttribute('data-desktop-sidebar', 'collapsed')
    await expect(serverPage.locator('#app-sidebar')).toBeHidden()
    await expect(serverPage.locator('[data-app-header] img[alt="Carits"]')).toBeVisible()
    await serverOnly.close()
    await context.close()
  })

  test('student receives direct home and submission entries', async ({ browser }) => {
    const context = await browser.newContext({ storageState: accounts.campusStudent.storageState })
    const page = await context.newPage()
    await page.goto(`${organizationBase}/overview`)
    const navigation = page.getByRole('navigation', { name: '学生主导航' })
    await expect(navigation.getByRole('link', { name: '首页' })).toBeVisible()
    await navigation.getByRole('link', { name: '评测记录' }).click()
    await expect(page).toHaveURL(`${organizationBase}/submissions`)
    await expect(page.getByRole('heading', { name: '评测记录' })).toBeVisible()
    await context.close()
  })

  test('training list uses the current school role instead of exposing manager actions to students', async ({ browser }) => {
    const studentContext = await browser.newContext({ storageState: accounts.campusStudent.storageState })
    const studentPage = await studentContext.newPage()
    await studentPage.goto(`${organizationBase}/training-sessions`)
    await expect(studentPage.getByRole('heading', { name: '训练', exact: true })).toBeVisible()
    await expect(studentPage.getByText('查看老师安排的训练并继续练习。')).toBeVisible()
    await expect(studentPage.getByRole('button', { name: '布置训练' })).toHaveCount(0)
    await expect(studentPage.getByRole('tab', { name: /进行中/ })).toBeVisible()
    await expect(studentPage.getByRole('tab', { name: /待开始/ })).toBeVisible()
    await expect(studentPage.getByRole('tab', { name: /已完成/ })).toBeVisible()
    await expect(studentPage.getByText('教练带练模式')).toHaveCount(0)
    await studentContext.close()
    const teacherContext = await browser.newContext({ storageState: accounts.teacher.storageState })
    const teacherPage = await teacherContext.newPage()
    await teacherPage.goto(`${organizationBase}/training-sessions`)
    await expect(teacherPage.getByText('管理和布置学生训练。')).toBeVisible()
    await expect(teacherPage.locator('header').getByRole('button', { name: '布置训练' })).toBeVisible()
    await expect(teacherPage.getByRole('tab', { name: /草稿/ })).toBeVisible()
    await expect(teacherPage.getByLabel('搜索训练')).toBeVisible()
    await teacherContext.close()
  })

  test('contest creation exposes all five decisions before the final write', async ({ browser }) => {
    const context = await browser.newContext({ storageState: accounts.principal.storageState })
    const page = await context.newPage()
    await page.goto(`${organizationBase}/contests`)
    await page.getByRole('button', { name: '创建比赛' }).click()
    const createDialog = page.getByRole('dialog', { name: '创建比赛' })
    await expect(createDialog.getByRole('button', { name: '1. 基本信息' })).toHaveAttribute('aria-current', 'step')
    await page.getByPlaceholder('比赛名称').fill('五步向导浏览器验收')
    await createDialog.getByRole('button', { name: '下一步' }).click()
    await expect(createDialog.getByLabel('比赛赛制')).toBeVisible()
    await expect(createDialog.getByLabel('Rating 范围')).toHaveValue('NONE')
    await createDialog.getByRole('button', { name: '下一步' }).click()
    // The current product uses canonical platform + problem code, not the retired library picker.
    await createDialog.getByLabel('题目平台').selectOption('carits')
    await createDialog.getByLabel('题号', { exact: true }).fill('E2E-1000')
    await createDialog.getByRole('button', { name: '添加', exact: true }).click()
    await expect(createDialog.locator('[aria-label="已选比赛题目"]')).toContainText('E2E A Plus B')
    await createDialog.getByRole('button', { name: '下一步' }).click()
    await expect(createDialog.getByText('题目来源显示')).toBeVisible()
    await expect(createDialog.getByText('题解显示')).toBeVisible()
    await createDialog.getByRole('button', { name: '下一步' }).click()
    await expect(createDialog.getByRole('heading', { name: '发布前检查' })).toBeVisible()
    await expect(createDialog.getByText(/创建时固定各题当前评测数据版本/)).toBeVisible()
    // Do not create a contest; this acceptance case verifies the complete pre-submit UI.
    await context.close()
  })

  test('unknown and forbidden organization routes explain the problem without changing location', async ({ browser }) => {
    const teacherContext = await browser.newContext({ storageState: accounts.teacher.storageState })
    const teacherPage = await teacherContext.newPage()
    await teacherPage.goto(`${organizationBase}/definitely-missing`)
    await expect(teacherPage).toHaveURL(`${organizationBase}/definitely-missing`)
    await expect(teacherPage.getByRole('heading', { name: '这里没有这个学校页面' })).toBeVisible()
    await teacherContext.close()
    const studentContext = await browser.newContext({ storageState: accounts.campusStudent.storageState })
    const studentPage = await studentContext.newPage()
    await studentPage.goto(`${organizationBase}/management`)
    await expect(studentPage).toHaveURL(`${organizationBase}/management`)
    await expect(studentPage.getByRole('heading', { name: '无法访问该页面' })).toBeVisible()
    await expect(studentPage.getByText(/学生身份/)).toBeVisible()
    await studentContext.close()
  })
})
