import fs from 'node:fs'
import { describe, expect, it } from 'vitest'

const read = (path: string) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')

describe('human UX productization contract', () => {
  it('uses a simple training flow and keeps coach controls optional', () => {
    const source = read('../features/training-session/ui/TrainingSessionListPage.tsx')
    const setup = read('../features/training-session/ui/TrainingSetupDialog.tsx')
    expect(source).toContain('布置训练')
    expect(source).toContain('管理和布置学生训练。')
    expect(setup).toContain('继续课堂设置')
    expect(setup).toContain('canContinueClassroomSetup')
    expect(setup).toContain('canPublishDirectly')
    expect(setup).toContain('timeRangeValid')
    expect(setup).toContain('当前设置')
    expect(setup).not.toContain('转为课堂训练')
    expect(setup).not.toContain('发布摘要')
    expect(setup).toContain('发布训练')
    expect(setup).toContain('requiredProblemCount')
    expect(setup).toContain('ProblemListEditor')
    expect(setup).toContain('renderTrailing')
    expect(setup).toContain("<Checkbox label={current.required ? '必做' : '选做'}")
    expect(setup).not.toContain('ProblemReferenceSelector')
    expect(setup).toContain('学生需要完成全部必做题')
    expect(setup).toContain("sessionType: 'GENERAL'")
    expect(setup).toContain("rankingMode: 'PROGRESS_ONLY'")
    expect(setup).toContain("peerVisibility: 'PROGRESS'")
    expect(setup).toContain("joinMode: 'CURRENT_STAGE'")
    expect(setup).toContain('allowHints: true')
    expect(setup).toContain("resultVisibility: 'LIVE'")
    expect(setup).toContain("mode: 'PRACTICE'")
    expect(setup).toContain("endPolicy: 'MANUAL'")
    expect(setup).not.toContain('templateKey')
    expect(setup).not.toContain('listTrainingTemplates')
    expect(setup).not.toContain('训练模板')
    expect(setup).not.toContain('使用场景')
    expect(setup).not.toContain('OI 模拟测试')
    expect(setup).not.toContain('ACM 模拟测试')
    expect(setup).not.toContain('至少完成指定题数')
    expect(source).toContain('trainingStatusLabel(item.status)')
    expect(source).not.toContain('trainingSessionTypeLabel(item.sessionType)')
    expect(source).not.toContain('快速训练')
    expect(source).not.toContain('多阶段训练')
    expect(source).not.toContain('creationModeGrid')
    expect(source).not.toContain('simpleStep')
    expect(source).not.toContain('>{item.status}</StatusBadge>')
  })

  it('separates student training language and actions from the manager view', () => {
    const source = read('../features/training-session/ui/TrainingSessionListPage.tsx')
    expect(source).toContain("user?.organizationRole === 'teacher'")
    expect(source).toContain("user?.organizationRole === 'school_principal'")
    expect(source).toContain("managerView ? '管理和布置学生训练。' : '查看老师安排的训练并继续练习。'")
    expect(source).toContain("actions={canCreateTraining ?")
    expect(source).toContain('目前老师还没有给你安排需要完成的训练')
    expect(source).toContain("label: '进行中'")
    expect(source).toContain("label: '待开始'")
    expect(source).toContain("label: '已完成'")
    expect(source).not.toContain('title="训练场次"')
    expect(source).not.toContain('共 ${sessions.length} 场')
  })

  it('describes ordinary training with tasks and gives school managers a team filter', () => {
    const source = read('../features/training-session/ui/TrainingSessionListPage.tsx')
    expect(source).not.toContain('${item._count.Stages} 个阶段')
    expect(source).toContain('${item.problemCount || 0} 道题')
    expect(source).toContain('全部训练范围')
    expect(source).toContain('校级训练')
    expect(source).toContain("item.status === 'DRAFT' ? '继续编辑'")
    expect(source).toContain("item.status === 'RUNNING' || item.status === 'PAUSED' ? '进入课堂'")
    expect(source).not.toContain('快速创建只适合“单阶段·全班统一”')
    expect(source).not.toContain('productMode')
  })

  it('uses progressive stage planning instead of an upfront stage matrix', () => {
    const designer = read('../features/training-session/ui/TrainingSessionDesigner.tsx')
    const workspace = read('../features/training-session/ui/TrainingSessionWorkspace.tsx')
    const runtimePanels = read('../features/training-session/ui/TrainingRuntimePanels.tsx')
    expect(designer).toContain('准备下一阶段')
    expect(designer).toContain('设置第一个阶段')
    expect(designer).toContain('沿用当前题目')
    expect(designer).toContain('从本次训练已有题目选择')
    expect(designer).toContain('ProblemListEditor')
    expect(designer).not.toContain('TrainingStageTimeline')
    expect(designer).not.toContain('TrainingStageGroupMatrix')
    expect(designer).not.toContain('copyStageAsDraft')
    expect(designer).not.toContain('选择多个阶段')
    expect(workspace).toContain('接下来做什么？')
    expect(workspace).toContain('继续当前阶段')
    expect(workspace).toContain('使用已准备阶段')
    expect(workspace).toContain('修改已准备阶段')
    expect(workspace).toContain('丢弃')
    expect(workspace).toContain('结束训练')
    expect(workspace).toContain('旧版多阶段训练')
    expect(workspace).toContain('trainingPermissionReasonLabel')
    expect(runtimePanels).toContain('完成当前阶段')
    expect(workspace).toContain('TrainingParticipantDrawer')
    expect(workspace).toContain('提前结束当前阶段')
    expect(workspace).toContain('调整分组')
    expect(workspace).toContain('加入学员')
    expect(workspace).toContain('追加训练题')
    expect(workspace).toContain('下一阶段生效')
    expect(workspace).not.toContain('复制当前阶段为未来阶段')
    expect(workspace).not.toContain('上一阶段')
  })

  it('does not block organization entry on workspace discovery', () => {
    const orgPage = read('../app/org/[organizationId]/[module]/page.tsx')
    const switcher = read('../features/workspace/ui/WorkspaceSwitcher.tsx')
    expect(orgPage).not.toContain('listWorkspaces')
    expect(orgPage).not.toContain('setReady')
    expect(orgPage).not.toContain('if (!ready')
    expect(orgPage).not.toContain("return null")
    expect(orgPage).toContain('user?.organizationId === organizationId')
    expect(switcher).toContain("const openSwitcher = async (initialFocus: 'first' | 'last' = 'first') =>")
    expect(switcher).toContain('if (loaded || directory.refreshing || !directoryEnabled) return')
    expect(switcher).toContain('void openSwitcher()')
  })

  it('keeps the sidebar account footer account-only and uses human workspace roles', () => {
    const shell = read('./AppShell.tsx')
    const switcher = read('../features/workspace/ui/WorkspaceSwitcher.tsx')
    const routing = read('../features/workspace/model/workspaceRouting.ts')
    expect(shell).toContain("isPersonal ? '个人账号' : `@${user.username}`")
    expect(shell).toContain('id="app-sidebar-close"')
    expect(shell).toContain('<PanelLeftClose')
    expect(switcher).toContain('workspaceRoleLabel')
    expect(routing).toContain("label === '本校学生'")
    expect(routing).toContain("return '学生'")
  })

  it('treats a team as an activity container instead of another workspace', () => {
    const source = read('../features/team/ui/TeamDetailPage.tsx')
    expect(source).toContain('<TeamActivityOverview')
    expect(source).toContain('<TeamMemberList')
    expect(source).not.toContain('TeamProblemListsTab')
    expect(source).not.toContain('TeamContestList')
  })

  it('shows a teacher task inbox before secondary statistics', () => {
    const source = read('./organization-pages/teacher/page.tsx')
    expect(source).toContain('待处理事项')
    expect(source).toContain('加入申请')
    expect(source).toContain('作业')
    expect(source).toContain('训练')
    expect(source).toContain("user?.organizationRole === 'school_principal'")
    expect(source).not.toContain("user?.role === 'school_principal'")
    expect(source).toContain('compareDashboardTasks')
    expect(source).toContain('contestResource')
    expect(source).toContain('teamResource.data?.total')
    expect(source).toContain('summary?.memberCount')
    expect(source).toContain('organizationId=${encodeURIComponent(organizationId)}&view=mine')
    expect(source).toContain('课后独立完成')
    expect(source).toContain('课堂分阶段训练')
    expect(source).toContain('定时竞赛')
  })

  it('builds the student task inbox from assignments, training and contests without counting the displayed slice', () => {
    const source = read('./organization-pages/student/page.tsx')
    expect(source).toContain('assignmentTasks')
    expect(source).toContain('trainingTasks')
    expect(source).toContain('contestTasks')
    expect(source).toContain('displayedTasks = pendingTasks.slice(0, 5)')
    expect(source).toContain('pendingTaskCount')
    expect(source).toContain('learningAllFailed')
    expect(source).toContain('部分学习任务暂时无法加载')
    expect(source).toContain('提交总数')
    expect(source).not.toContain('>{nextTasks.length}</p>')
  })

  it('makes school training targets explicit and keeps team navigation canonical', () => {
    const training = read('../features/training-session/ui/TrainingSessionListPage.tsx')
    const setup = read('../features/training-session/ui/TrainingSetupDialog.tsx')
    const contests = read('./organization-pages/teacher/contests/page.tsx')
    const activities = read('../features/team/ui/TeamActivityOverview.tsx')
    expect(setup).toContain('团队（推荐）')
    expect(setup).toContain('自定义学生')
    expect(setup).toContain('全校学生')
    expect(training).toContain("searchParams.get('teamId')")
    expect(contests).toContain("searchParams.get('teamId')")
    expect(contests).toContain('basePath={pathPrefix}')
    expect(activities).toContain("item.kind === 'training' ? '训练'")
    expect(activities).not.toContain("item.kind === 'training' ? '教练训练'")
  })

  it('uses an inline submission workbench and merges personal solutions', () => {
    const source = read('../features/problem/ui/ProblemDetail.tsx')
    expect(source).toContain('aria-label="代码提交工作台"')
    expect(source).toContain('撰写我的题解')
    expect(source).toContain('label="题目更多内容"')
    expect(source).toContain('trigger={<Button variant="outline">管理题目</Button>}')
    expect(source).not.toContain("handleTabChange('my-content')")
    expect(source).toContain("setActiveTab(VALID_TABS.includes(tab) ? tab : 'statement')")
    expect(source).toContain('new URLSearchParams(searchParams.toString())')
    expect(source).toContain("if (tab === 'statement') next.delete('tab')")
    expect(source).not.toContain('同步远程记录')
    expect(source).toContain('<Pagination')
    expect(source).toContain('problemSubmissionsError')
    expect(source).toContain('不会把加载失败误判为题目被删除')
    expect(source).toContain('代码和文件 IO 设置已保留')
    expect(source).not.toContain('clearSubmissionDraft')
    expect(source).not.toContain('onClick={() => setDetailSubmissionId(s.id)}\n                          className')
  })

  it('keeps student views free of internal revision terminology', () => {
    const assignment = read('../features/assignment/ui/AssignmentWorkspace.tsx')
    const training = read('../features/training-session/ui/TrainingSessionWorkspace.tsx')
    expect(assignment).toContain('每次提交使用当时可用的评测数据')
    expect(training).toContain('提交时使用当前训练数据评测')
    expect(assignment).not.toContain('Stable')
    expect(training).not.toContain('Evolving')
    expect(assignment).not.toContain('TestSet Revision 与学生名单')
    expect(assignment).not.toContain('版本号并发校验')
    expect(assignment).not.toContain('成绩快照 v')
    expect(training).not.toContain('命令带 revision 审计')
  })

  it('renders quality conclusions and hides technical certificates by default', () => {
    const source = read('../features/problem/ui/ProblemQualityPanel.tsx')
    expect(source).toContain('数据质量良好')
    expect(source).toContain('查看质量指标与评估依据')
  })

  it('does not ask users to type resource IDs in the data market', () => {
    const source = read('../features/data-market/ui/DataMarketplace.tsx')
    expect(source).toContain('<ProblemSlotPicker')
    expect(source).toContain('<LicenseScopePicker')
    expect(source).not.toContain('Problem ID')
    expect(source).not.toContain('组织 ID')
    expect(source).not.toContain('比赛 ID')
  })

  it('does not ask blog authors to paste internal database identifiers', () => {
    const source = read('../features/blog/ui/BlogReferenceEditor.tsx')
    expect(source).toContain('<ProblemReferencePicker')
    expect(source).toContain('请到对应的题解、比赛榜单或 Rating 记录页面')
    expect(source).not.toContain('内部 ID')
    expect(source).not.toContain('Revision ID')
    expect(source).not.toContain('Snapshot ID')
  })

  it('uses school language in the school workspace and hides account internals', () => {
    const school = read('./organization-pages/teacher/school/components/HomeTab.tsx')
    const wallet = read('../features/account-wallet/ui/WalletPage.tsx')
    expect(school).toContain('学校资产')
    expect(school).not.toContain('组织钱包')
    expect(wallet).toContain('我的钱包与评测额度')
    expect(wallet).toContain('使用详情与兑换记录')
    expect(wallet).toContain('学校贡献归属已记录')
  })

  it('uses human contribution language outside the manager-only technical view', () => {
    const source = read('../features/problem/ui/ProblemHackPanel.tsx')
    expect(source).toContain('系统会依次检查输入是否合法')
    expect(source).toContain('贡献候选数据')
    expect(source).toContain('选择学校只用于贡献记录归属')
    expect(source).not.toContain('选择组织只用于声誉归因')
  })

  it('keeps shared feedback and overlays keyboard accessible', () => {
    const toast = read('./ui/Toast.tsx')
    const dialogs = read('./ui/Dialogs.tsx')
    const tabs = read('./ui/Tabs.tsx')
    const overlays = read('./ui/OverlayPrimitives.tsx')
    expect(toast).toContain("role={item.type === 'error' ? 'alert' : 'status'}")
    expect(toast).toContain("aria-live={item.type === 'error' ? 'assertive' : 'polite'}")
    expect(dialogs).toContain('<form id={formId} onSubmit={submit} noValidate>')
    expect(tabs).toContain("['ArrowLeft', 'ArrowRight', 'Home', 'End']")
    expect(overlays).toContain("['ArrowDown', 'ArrowUp', 'Home', 'End']")
    expect(overlays).toContain('triggerRef.current?.focus()')
  })

  it('preserves user work and distinguishes request failures from empty results', () => {
    const chat = read('../features/chat/ui/ChatWorkspace.tsx')
    const organizations = read('../features/organization-account/ui/PersonalOrganizationsPage.tsx')
    const switcher = read('../features/workspace/ui/WorkspaceSwitcher.tsx')
    const market = read('../features/data-market/ui/DataMarketplace.tsx')
    const note = read('../features/problem/ui/ProblemNote.tsx')
    expect(chat).toContain('chat-drafts:')
    expect(chat).toContain('draftsLoadedFor')
    expect(organizations).toContain('directoryError')
    expect(organizations).toContain('没有将网络错误显示成“没有找到学校”')
    expect(switcher).toContain('loadError')
    expect(switcher).toContain('当前身份不会改变')
    expect(market).toContain('Promise.allSettled')
    expect(note).toContain('noteSaveError')
    expect(note).toContain('内容仍保留在编辑器中')
  })

  it('uses one searchable roster table for large-class grouping', () => {
    const source = read('../features/training-session/ui/TrainingDesignAuxiliary.tsx')
    expect(source).toContain('统一维护训练名单与分组')
    expect(source).toContain('全选当前筛选结果')
    expect(source).toContain('批量目标分组')
    expect(source).toContain('移出训练名单')
    expect(source).toContain('名已选学员尚未分组')
    expect(source).not.toContain("roster?.candidates.filter(candidate => candidate.selected).map(candidate => <Checkbox")
  })

  it('makes training realtime and batch controls explicit and safe', () => {
    const source = read('../features/training-session/ui/TrainingSessionWorkspace.tsx')
    expect(source).toContain('scheduleReload')
    expect(source).toContain('最后同步')
    expect(source).toContain('重新加载训练')
    expect(source).toContain('splitTrainingGroup')
    expect(source).toContain('mergeTrainingGroup')
    expect(source).toContain('joinTrainingParticipantRuntime')
    expect(source).toContain('leaveTrainingParticipantRuntime')
    expect(source).toContain('appendTrainingRuntimeProblem')
    expect(source).toContain('所有分组共享同一个阶段时间轴')
    expect(source).toContain('TrainingAttentionPanel')
    expect(source).toContain('TrainingRuntimeHeader')
    expect(source).toContain('data.session.currentStageId')
    expect(source).not.toContain('group.StageGroups?.find')
    expect(source).toContain('暂停提交（可继续编辑）')
    expect(source).toContain('暂停提交与编辑')
    expect(source).not.toContain('>{runtimeStatus}</StatusBadge>')
    expect(source).not.toContain('>软暂停</Button>')
    expect(source).not.toContain('>硬暂停</Button>')
    expect(source).toContain('function StageTimeMetrics')
    expect(source).not.toContain('setClockNow')
  })

  it('keeps organization joining honest on deep links and read failures', () => {
    const source = read('../features/organization-account/ui/OrganizationJoinManagement.tsx')
    expect(source).toContain('selectApplication(linkedApplication)')
    expect(source).toContain('没有将读取失败显示成“暂无申请”')
    expect(source).toContain('没有将读取失败显示成“暂无邀请”')
    expect(source).toContain('当前策略未知，未使用默认值代替')
    expect(source).toContain('重新加载加入设置')
    expect(source).toContain('重试教师列表')
    expect(source).toContain('(!listError || items.length > 0)')
  })

  it('keeps archive import out of activity submission guidance', () => {
    const source = read('../features/contest/ui/ContestDetailPage.tsx')
    expect(source).toContain('提交结果只计入当前活动')
    expect(source).not.toContain('远程提交记录可在题目页同步归档')
  })
})
