'use client'

import { useCallback, useEffect, useState } from 'react'
import { Database, FileKey2, Plus, RefreshCw, ShieldAlert } from 'lucide-react'
import apiClient from '@/lib/apiClient'
import { createClientUUID } from '@/lib/uuid'
import { useAuth } from '@/components/AuthProvider'
import { useToast } from '@/components/ui/Toast'
import { PageFrame } from '@/components/ui/PageFrame'
import { PageHeader } from '@/components/ui/PageHeader'
import { Button } from '@/components/ui/Button'
import { Badge } from '@/components/ui/Badge'
import { FormDialog, DetailDialog } from '@/components/ui/Dialogs'
import { Input, Select, Textarea } from '@/components/ui/FormControls'
import styles from './DataMarketplace.module.css'
import { buildDataPurchasePayload, canManageDataMarketplace, canRequestDataUpgrade, type DataLicense } from './data-market'

type Price = { id: string; licenseType: DataLicense; amountCarits: string }
type Certificate = { overallScore: number; correctnessScore: number; discriminationScore: number; coverageScore: number; diversityScore: number; confidenceLevel: string; maturityLevel: string; qualityRuleVersion: string }
type Product = { id: string; problemId: string; revisionId: string; grade: string; updatePolicy: string; status: string; includes: Record<string, boolean>; Problem: { problemId: string; title: string }; Revision: { revisionNumber: number; graphHash: string }; QualitySnapshot: Certificate; Prices: Price[] }
type Entitlement = { id: string; licenseType: string; updatesUntil?: string | null; revokedAt?: string | null; Purchase: { Product: { id: string; updatePolicy: string; Problem: { problemId: string; title: string } } }; Revisions: Array<{ id: string; sequence: number; testSetRevisionId: string; grantReason: string; TestSetRevision: { revisionNumber: number }; QualitySnapshot: Certificate }> }
type Incident = { id: string; problemId: string; revisionId: string; severity: string; type: string; description: string; status: string; fixedByRevisionId?: string | null; discoveredAt: string }

const licenseLabel = { PERSONAL: '个人', ORGANIZATION: '组织', CONTEST: '比赛' }
const gradeLabel: Record<string,string> = { COMMUNITY: '社区级', VERIFIED: '已验证', COMPETITION_GRADE: '竞赛级' }

export function DataMarketplace() {
  const { user } = useAuth(); const toast = useToast()
  const [tab,setTab]=useState<'market'|'owned'|'manage'>('market'); const [products,setProducts]=useState<Product[]>([]); const [entitlements,setEntitlements]=useState<Entitlement[]>([]); const [loading,setLoading]=useState(true)
  const [selected,setSelected]=useState<Product|null>(null); const [buying,setBuying]=useState<Product|null>(null); const [license,setLicense]=useState<Price['licenseType']>('PERSONAL'); const [organizationId,setOrganizationId]=useState(''); const [contestId,setContestId]=useState(''); const [busy,setBusy]=useState(false)
  const [manifest,setManifest]=useState<unknown>(null); const [manifestTitle,setManifestTitle]=useState('')
  const [publishOpen,setPublishOpen]=useState(false); const [publish,setPublish]=useState({problemId:'',revisionId:'',qualitySnapshotId:'',updatePolicy:'SNAPSHOT'})
  const [incidentOpen,setIncidentOpen]=useState(false); const [incident,setIncident]=useState({revisionId:'',severity:'CRITICAL',type:'',description:''})
  const [incidentProblemId,setIncidentProblemId]=useState(''); const [incidents,setIncidents]=useState<Incident[]>([]); const [incidentFixes,setIncidentFixes]=useState<Record<string,string>>({})
  const [upgradeTarget,setUpgradeTarget]=useState<Record<string,string>>({})
  const canManage=canManageDataMarketplace(user?.role,user?.organizationRole)

  const load=useCallback(async()=>{setLoading(true);const [market,owned]=await Promise.all([apiClient.get<Product[]>('/api/data-products'),apiClient.get<Entitlement[]>('/api/data-entitlements')]);if(market.success)setProducts(market.data||[]);else toast.error(market.message||'读取数据商品失败');if(owned.success)setEntitlements(owned.data||[]);else toast.error(owned.message||'读取授权失败');setLoading(false)},[]) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{void load()},[load])

  const openBuy=(product:Product, selectedLicense?:Price['licenseType'])=>{setBuying(product);setLicense(selectedLicense||product.Prices[0]?.licenseType||'PERSONAL');setOrganizationId(user?.organizationId||'');setContestId('')}
  const buy=async()=>{if(!buying)return;setBusy(true);const body=buildDataPurchasePayload(license,organizationId,contestId);const result=await apiClient.request(`/api/data-products/${buying.id}/purchase`,{method:'POST',headers:{'Idempotency-Key':createClientUUID()},body});setBusy(false);if(!result.success)return toast.error(result.message||'购买失败');toast.success('购买成功，固定版本授权已生成');setBuying(null);await load()}
  const createProduct=async()=>{setBusy(true);const result=await apiClient.post(`/api/problems/${publish.problemId}/data-products`,{revisionId:publish.revisionId,qualitySnapshotId:publish.qualitySnapshotId,updatePolicy:publish.updatePolicy,allowedLicenses:['PERSONAL','ORGANIZATION','CONTEST'],includes:{testdata:true,checker:true}});setBusy(false);if(!result.success)return toast.error(result.message||'发布失败');toast.success('商品已按质量快照自动定级定价');setPublishOpen(false);await load()}
  const loadIncidents=async(problemId=incidentProblemId)=>{if(!problemId.trim())return toast.warning('请输入 Problem ID');setBusy(true);const result=await apiClient.get<Incident[]>(`/api/problems/${encodeURIComponent(problemId.trim())}/test-set-quality-incidents`);setBusy(false);if(!result.success)return toast.error(result.message||'读取事故失败');setIncidents(result.data||[])}
  const createIncident=async()=>{setBusy(true);const result=await apiClient.post<Incident>('/api/test-set-quality-incidents',{...incident,evidence:{reportedFrom:'data-market-web'}});setBusy(false);if(!result.success)return toast.error(result.message||'登记失败');toast.success(incident.severity==='CRITICAL'?'严重事故已登记，相关商品已停售':'质量事故已登记');setIncidentOpen(false);if(result.data?.problemId){setIncidentProblemId(result.data.problemId);await loadIncidents(result.data.problemId)}await load()}
  const confirmIncident=async(id:string)=>{setBusy(true);const result=await apiClient.post(`/api/test-set-quality-incidents/${id}/confirm`);setBusy(false);if(!result.success)return toast.error(result.message||'确认失败');toast.success('质量事故已确认');await loadIncidents()}
  const resolveIncident=async(id:string)=>{const fixedByRevisionId=incidentFixes[id]?.trim();setBusy(true);const result=await apiClient.post(`/api/test-set-quality-incidents/${id}/resolve`,fixedByRevisionId?{fixedByRevisionId}:{});setBusy(false);if(!result.success)return toast.error(result.message||'解决事故失败');toast.success('事故已解决，符合条件的授权已追加修复版本');await loadIncidents()}
  const viewManifest=async(item:Entitlement,revision:Entitlement['Revisions'][number])=>{setBusy(true);const result=await apiClient.get(`/api/data-entitlements/${item.id}/revisions/${revision.testSetRevisionId}/manifest`);setBusy(false);if(!result.success)return toast.error(result.message||'读取授权清单失败');setManifest(result.data);setManifestTitle(`${item.Purchase.Product.Problem.title} · R${revision.TestSetRevision.revisionNumber}`)}
  const upgrade=async(item:Entitlement)=>{const dataProductId=upgradeTarget[item.id]?.trim();if(!dataProductId)return toast.warning('请输入同题更新商品 ID');setBusy(true);const result=await apiClient.post(`/api/data-entitlements/${item.id}/upgrades`,{dataProductId});setBusy(false);if(!result.success)return toast.error(result.message||'升级失败');toast.success('已追加新授权版本，原版本保持不变');await load()}

  return <PageFrame width="workbench"><PageHeader title="题目数据市场" description="商品固定绑定不可变测试集 Revision 与质量证书；购买价格由服务端决定。" actions={<Button variant="outline" icon={<RefreshCw size={16}/>} onClick={()=>void load()}>刷新</Button>}/>
    <div className={styles.tabs}><Button variant={tab==='market'?'primary':'ghost'} onClick={()=>setTab('market')}>数据商品</Button><Button variant={tab==='owned'?'primary':'ghost'} onClick={()=>setTab('owned')}>我的授权</Button>{canManage&&<Button variant={tab==='manage'?'primary':'ghost'} onClick={()=>setTab('manage')}>发布与事故</Button>}</div>
    {loading?<div className={styles.empty}>正在加载…</div>:tab==='market'?<div className={styles.grid}>{products.length===0?<div className={styles.empty}>暂无可售数据商品</div>:products.map(product=><article className={styles.card} key={product.id}><div className={styles.badges}><Badge variant="success">{gradeLabel[product.grade]||product.grade}</Badge><Badge variant="neutral">R{product.Revision.revisionNumber}</Badge><Badge variant="info">{product.updatePolicy}</Badge></div><h2>{product.Problem.title}</h2><p className={styles.muted}>{product.Problem.problemId} · DQS {product.QualitySnapshot.overallScore} · {product.QualitySnapshot.confidenceLevel}/{product.QualitySnapshot.maturityLevel}</p><div className={styles.actions}>{product.Prices.map(price=><Button size="sm" key={price.id} onClick={()=>openBuy(product,price.licenseType)}>{licenseLabel[price.licenseType]} {price.amountCarits} C</Button>)}<Button size="sm" variant="outline" onClick={()=>setSelected(product)}>查看证书</Button></div></article>)}</div>
    :tab==='owned'?<div className={styles.grid}>{entitlements.length===0?<div className={styles.empty}>尚未购买数据授权</div>:entitlements.map(item=><article className={styles.card} key={item.id}><div className={styles.badges}><Badge>{licenseLabel[item.licenseType as keyof typeof licenseLabel]||item.licenseType}</Badge>{item.updatesUntil&&<Badge variant="neutral">更新至 {new Date(item.updatesUntil).toLocaleDateString()}</Badge>}</div><h2>{item.Purchase.Product.Problem.title}</h2><p className={styles.muted}>授权 ID：{item.id}</p>{item.Revisions.map(revision=><div className={styles.revision} key={revision.id}><strong>R{revision.TestSetRevision.revisionNumber}</strong><p className={styles.muted}>{revision.grantReason} · DQS {revision.QualitySnapshot.overallScore}</p><Button size="sm" variant="outline" icon={<FileKey2 size={14}/>} disabled={busy} onClick={()=>void viewManifest(item,revision)}>授权清单与下载</Button></div>)}{canRequestDataUpgrade(item.Purchase.Product.updatePolicy)&&<div className={styles.actions}><Input placeholder="同题更新商品 ID" value={upgradeTarget[item.id]||''} onChange={event=>setUpgradeTarget(value=>({...value,[item.id]:event.target.value}))}/><Button size="sm" onClick={()=>void upgrade(item)} disabled={busy}>追加升级版本</Button></div>}</article>)}</div>
    :<div className={styles.grid}><section className={styles.panel}><Database size={22}/><h2>发布数据商品</h2><p className={styles.muted}>只提供 Problem、Revision 与 Quality Snapshot；等级和三种许可证价格由服务端生成。</p><Button icon={<Plus size={16}/>} onClick={()=>setPublishOpen(true)}>发布商品</Button></section><section className={styles.panel}><ShieldAlert size={22}/><h2>登记质量事故</h2><p className={styles.muted}>Critical 会立即停售绑定该 Revision 的商品并通知已有购买者。</p><Button variant="danger" onClick={()=>setIncidentOpen(true)}>登记事故</Button></section><section className={`${styles.panel} ${styles.wide}`}><h2>事故状态与修复</h2><div className={styles.actions}><Input placeholder="Problem ID" value={incidentProblemId} onChange={event=>setIncidentProblemId(event.target.value)}/><Button variant="outline" disabled={busy} onClick={()=>void loadIncidents()}>查询事故</Button></div>{incidents.length===0?<p className={styles.muted}>输入可管理的 Problem ID 查询事故记录。</p>:incidents.map(item=><div className={styles.revision} key={item.id}><div className={styles.badges}><Badge variant={item.severity==='CRITICAL'?'error':'neutral'}>{item.severity}</Badge><Badge>{item.status}</Badge></div><strong>{item.type} · Revision {item.revisionId}</strong><p className={styles.muted}>{item.description}</p>{item.status==='OPEN'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void confirmIncident(item.id)}>确认事故</Button>}{item.status!=='RESOLVED'&&<div className={styles.actions}><Input placeholder={item.severity==='CRITICAL'?'认证修复 Revision ID（必填）':'修复 Revision ID（可选）'} value={incidentFixes[item.id]||''} onChange={event=>setIncidentFixes(value=>({...value,[item.id]:event.target.value}))}/><Button size="sm" disabled={busy} onClick={()=>void resolveIncident(item.id)}>解决并追加修复授权</Button></div>}</div>)}</section></div>}

    <DetailDialog isOpen={Boolean(selected)} onClose={()=>setSelected(null)} title="数据质量证书" description={selected?`${selected.Problem.problemId} · Revision ${selected.Revision.revisionNumber}`:undefined}>{selected&&<div className={styles.certificate}><div><strong>{selected.QualitySnapshot.overallScore}/100</strong><span>DQS</span></div><div><strong>{selected.QualitySnapshot.correctnessScore}/30</strong><span>Correctness</span></div><div><strong>{selected.QualitySnapshot.discriminationScore}/25</strong><span>Discrimination</span></div><div><strong>{selected.QualitySnapshot.coverageScore}/15</strong><span>Coverage</span></div><div><strong>{selected.QualitySnapshot.confidenceLevel}</strong><span>Confidence</span></div><div><strong>{selected.QualitySnapshot.maturityLevel}</strong><span>Maturity</span></div></div>}</DetailDialog>
    <FormDialog isOpen={Boolean(buying)} onClose={()=>setBuying(null)} onSubmit={()=>void buy()} title="购买固定版本数据" description={buying?`${buying.Problem.title} · Revision ${buying.Revision.revisionNumber}`:undefined} submitText="确认购买" loading={busy}><div className={styles.form}><label className={styles.field}>许可证<Select value={license} onChange={event=>setLicense(event.target.value as Price['licenseType'])}>{buying?.Prices.map(price=><option key={price.id} value={price.licenseType}>{licenseLabel[price.licenseType]} · {price.amountCarits} C</option>)}</Select></label>{license==='ORGANIZATION'&&<label className={styles.field}>组织 ID<Input value={organizationId} onChange={event=>setOrganizationId(event.target.value)}/></label>}{license==='CONTEST'&&<label className={styles.field}>比赛 ID（Training）<Input type="number" value={contestId} onChange={event=>setContestId(event.target.value)}/></label>}<p className={styles.muted}>价格在提交购买时由服务端重新读取；页面不会向接口发送金额。</p></div></FormDialog>
    <FormDialog isOpen={publishOpen} onClose={()=>setPublishOpen(false)} onSubmit={()=>void createProduct()} title="发布质量认证数据商品" submitText="发布" loading={busy} size="lg"><div className={styles.formGrid}><label className={styles.field}>Problem ID<Input value={publish.problemId} onChange={e=>setPublish(v=>({...v,problemId:e.target.value}))}/></label><label className={styles.field}>TestSet Revision ID<Input value={publish.revisionId} onChange={e=>setPublish(v=>({...v,revisionId:e.target.value}))}/></label><label className={`${styles.field} ${styles.wide}`}>Quality Snapshot ID<Input value={publish.qualitySnapshotId} onChange={e=>setPublish(v=>({...v,qualitySnapshotId:e.target.value}))}/></label><label className={styles.field}>更新策略<Select value={publish.updatePolicy} onChange={e=>setPublish(v=>({...v,updatePolicy:e.target.value}))}><option value="SNAPSHOT">仅当前版本</option><option value="UPDATE_90D">90 天更新</option><option value="LIFETIME_UPDATES">永久更新</option></Select></label></div></FormDialog>
    <FormDialog isOpen={incidentOpen} onClose={()=>setIncidentOpen(false)} onSubmit={()=>void createIncident()} title="登记测试集质量事故" submitText="登记" danger={incident.severity==='CRITICAL'} loading={busy} size="lg"><div className={styles.form}><label className={styles.field}>TestSet Revision ID<Input value={incident.revisionId} onChange={e=>setIncident(v=>({...v,revisionId:e.target.value}))}/></label><label className={styles.field}>严重程度<Select value={incident.severity} onChange={e=>setIncident(v=>({...v,severity:e.target.value}))}><option>INFO</option><option>MINOR</option><option>MAJOR</option><option>CRITICAL</option></Select></label><label className={styles.field}>事故类型<Input value={incident.type} onChange={e=>setIncident(v=>({...v,type:e.target.value}))}/></label><label className={styles.field}>说明<Textarea rows={5} value={incident.description} onChange={e=>setIncident(v=>({...v,description:e.target.value}))}/></label></div></FormDialog>
    <DetailDialog isOpen={manifest!==null} onClose={()=>setManifest(null)} title="授权数据清单" description={manifestTitle}><p className={styles.muted}>清单中的对象链接由服务端逐次复核授权；未购买组件不会出现在清单中。</p><pre className={styles.code}>{JSON.stringify(manifest,null,2)}</pre></DetailDialog>
  </PageFrame>
}
