import { Router } from 'express'
import { ProblemContracts } from '@oi-manager/contracts'
import { sendContractData, sendContractError } from '../../lib/api-contract'
import { authenticate } from '../../middleware/auth'
import { asyncHandler } from '../../lib/asyncHandler'
import { compileJudgeProgramVersion, createJudgeProgram, createJudgeProgramFixtureSet, createJudgeProgramVersion, deleteJudgeProgramDraft, getJudgeProgramCapabilities, getJudgeProgramVerification, JudgeProgramError, listJudgeProgramAuditLogs, listJudgeProgramDrafts, listJudgeProgramFixtureSets, listJudgePrograms, listJudgeProgramTemplates, preflightJudgeProgramVersion, readJudgeProgramTemplate, saveJudgeProgramDraft, updateJudgeProgram } from './problem.judge-program.service'
export const problemJudgeProgramRouter = Router()
export const judgeProgramTemplateRouter = Router()
function send(error: unknown, res: any) { if (!(error instanceof JudgeProgramError)) throw error; return res.status(error.statusCode).json({ success: false, code: error.code, message: error.message, ...(error.data === undefined ? {} : { data: error.data }) }) }
problemJudgeProgramRouter.get('/judge-program-templates', authenticate, asyncHandler(async (_req, res) => { sendContractData(res, ProblemContracts.listJudgeProgramTemplates, { ...getJudgeProgramCapabilities(), templates: listJudgeProgramTemplates() }) }))
problemJudgeProgramRouter.get('/judge-program-templates/:templateId', authenticate, asyncHandler(async (req, res) => { try { sendContractData(res, ProblemContracts.getJudgeProgramTemplate, readJudgeProgramTemplate(req.params.templateId)) } catch (error) { if (sendContractError(error, res)) return; return send(error, res) } }))
judgeProgramTemplateRouter.get('/judge-program-templates', authenticate, asyncHandler(async (_req, res) => { sendContractData(res, ProblemContracts.listJudgeProgramTemplates, { ...getJudgeProgramCapabilities(), templates: listJudgeProgramTemplates() }) }))
judgeProgramTemplateRouter.get('/judge-program-templates/:templateId', authenticate, asyncHandler(async (req, res) => { try { sendContractData(res, ProblemContracts.getJudgeProgramTemplate, readJudgeProgramTemplate(req.params.templateId)) } catch (error) { if (sendContractError(error, res)) return; return send(error, res) } }))
problemJudgeProgramRouter.get('/:id/judge-program-drafts', authenticate, asyncHandler(async (req, res) => { try { res.json({ success: true, data: await listJudgeProgramDrafts(req.user!, req.params.id) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.post('/:id/judge-program-drafts', authenticate, asyncHandler(async (req, res) => { try { res.status(201).json({ success: true, data: await saveJudgeProgramDraft({ user: req.user!, problemId: req.params.id, ...req.body }) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.patch('/:id/judge-program-drafts/:draftId', authenticate, asyncHandler(async (req, res) => { try { res.json({ success: true, data: await saveJudgeProgramDraft({ user: req.user!, problemId: req.params.id, draftId: req.params.draftId, ...req.body }) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.delete('/:id/judge-program-drafts/:draftId', authenticate, asyncHandler(async (req, res) => { try { res.json({ success: true, data: await deleteJudgeProgramDraft(req.user!, req.params.id, req.params.draftId) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.get('/:id/judge-programs', authenticate, asyncHandler(async (req, res) => { try { res.json({ success: true, data: await listJudgePrograms(req.user!, req.params.id) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.get('/:id/judge-program-audit-logs', authenticate, asyncHandler(async (req, res) => { try { res.json({ success: true, data: await listJudgeProgramAuditLogs(req.user!, req.params.id) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.post('/:id/judge-programs', authenticate, asyncHandler(async (req, res) => { try { res.status(201).json({ success: true, data: await createJudgeProgram({ user: req.user!, problemId: req.params.id, ...req.body }) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.post('/:id/judge-programs/:programId/versions', authenticate, asyncHandler(async (req, res) => { try { res.status(201).json({ success: true, data: await createJudgeProgramVersion({ user: req.user!, problemId: req.params.id, programId: req.params.programId, ...req.body }) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.post('/:id/judge-programs/:programId/fixture-sets', authenticate, asyncHandler(async (req, res) => { try { res.status(201).json({ success: true, data: await createJudgeProgramFixtureSet({ user: req.user!, problemId: req.params.id, programId: req.params.programId, fixtures: req.body?.fixtures }) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.get('/:id/judge-programs/:programId/fixture-sets', authenticate, asyncHandler(async (req, res) => { try { res.json({ success: true, data: await listJudgeProgramFixtureSets(req.user!, req.params.id, req.params.programId) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.post('/:id/judge-programs/:programId/versions/:versionId/compile', authenticate, asyncHandler(async (req, res) => { try { res.status(202).json({ success: true, data: await compileJudgeProgramVersion({ user: req.user!, problemId: req.params.id, programId: req.params.programId, versionId: req.params.versionId }) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.post('/:id/judge-programs/:programId/versions/:versionId/preflight', authenticate, asyncHandler(async (req, res) => { try { res.status(202).json({ success: true, data: await preflightJudgeProgramVersion({ user: req.user!, problemId: req.params.id, programId: req.params.programId, versionId: req.params.versionId, fixtureSetId: req.body?.fixtureSetId, fixtures: req.body?.fixtures }) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.get('/:id/judge-programs/:programId/versions/:versionId/verification', authenticate, asyncHandler(async (req, res) => { try { res.json({ success: true, data: await getJudgeProgramVerification(req.user!, req.params.id, req.params.programId, req.params.versionId) }) } catch (error) { return send(error, res) } }))
problemJudgeProgramRouter.patch('/:id/judge-programs/:programId', authenticate, asyncHandler(async (req, res) => { try { res.json({ success: true, data: await updateJudgeProgram({ user: req.user!, problemId: req.params.id, programId: req.params.programId, ...req.body }) }) } catch (error) { return send(error, res) } }))
