'use client'

import { Button } from '@/components/ui/Button'
import { JUDGE_RESULT_LABEL_MAP, LANGUAGE_LABEL_MAP } from '@/lib/judge-constants'
import type { TrainingInfo, TrainingProblem, SubmissionRow } from '../types'
import { LoadError } from '@/components/ui/LoadError'
import { SkeletonRegion } from '@/components/ui/AsyncRegion'
import { UserIdentityLink } from '@/components/profile/UserIdentityLink'
import styles from '../TrainingWorkspace.module.css'

const RESULT_COLORS: Record<string, { bg: string; text: string }> = { accepted: { bg: 'var(--success-light)', text: 'var(--success-text)' }, queuing: { bg: 'var(--info-light)', text: 'var(--info-text)' }, judging: { bg: 'var(--info-light)', text: 'var(--info-text)' }, tle: { bg: 'var(--warning-light)', text: 'var(--warning-text)' }, mle: { bg: 'var(--warning-light)', text: 'var(--warning-text)' }, wa: { bg: 'var(--error-light)', text: 'var(--error-text)' }, re: { bg: 'var(--error-light)', text: 'var(--error-text)' }, ce: { bg: 'var(--warning-light)', text: 'var(--text-secondary)' }, pe: { bg: 'var(--warning-light)', text: 'var(--warning-text)' }, ole: { bg: 'var(--warning-light)', text: 'var(--warning-text)' } }
function toExcelColumnName(index: number) { let result = ''; let i = index; while (i >= 0) { result = String.fromCharCode(65 + (i % 26)) + result; i = Math.floor(i / 26) - 1 } return result }
function resultBadge(result: string | null, hidden?: boolean, display?: string) { if (hidden || display === 'pending') return <span className={styles.submissionHidden}>已提交</span>; if (!result) return <span className={`${styles.result} ${styles.muted}`} style={{ background: 'var(--bg-muted)' }}>-</span>; const color = RESULT_COLORS[result] || { bg: 'var(--bg-muted)', text: 'var(--text-primary)' }; return <span className={styles.result} style={{ background: color.bg, color: color.text }}>{JUDGE_RESULT_LABEL_MAP[result] || result}</span> }

interface TrainingSubmissionPanelProps { training: TrainingInfo; problems: TrainingProblem[]; submissions: SubmissionRow[]; submissionsPage: number; submissionsTotal: number; filterProblemId: string; setFilterProblemId: (v: string) => void; filterUsername: string; setFilterUsername: (v: string) => void; filterResult: string; setFilterResult: (v: string) => void; filterLanguage: string; setFilterLanguage: (v: string) => void; setSubmissionsPage: (v: number | ((p: number) => number)) => void; resetFilters: () => void; onViewSubmission: (id: number) => void; onLanguageClick: (id: number) => void; loading?: boolean; error?: string | null; onRetry?: () => void }
export function TrainingSubmissionPanel(props: TrainingSubmissionPanelProps) {
  const { training, problems, submissions, submissionsPage, submissionsTotal, filterProblemId, setFilterProblemId, filterUsername, setFilterUsername, filterResult, setFilterResult, filterLanguage, setFilterLanguage, setSubmissionsPage, resetFilters, onViewSubmission, onLanguageClick, loading, error, onRetry } = props
  const hideOiResults = training.format === 'oi' && !training.isAdmin && training.runtimeStatus !== 'finished'; const hideProblemSource = !training.isAdmin && !training.problemIdVisible && training.runtimeStatus !== 'finished'; const scoreBased = training.format === 'oi' || training.format === 'ioi'; const pages = Math.ceil(submissionsTotal / 50)
  const change = (setter: (v: string) => void, value: string) => { setter(value); setSubmissionsPage(1) }
  return <div className={styles.surface}><div className={styles.filterBar}>{!hideProblemSource && <select aria-label="序号" value={filterProblemId} onChange={e => change(setFilterProblemId, e.target.value)}><option value="">全部题目</option>{problems.map(p => <option key={p.id} value={p.id}>{toExcelColumnName(p.orderIndex ?? 0)}</option>)}</select>}{training.isAdmin && <input className={styles.filterInput} value={filterUsername} onChange={e => change(setFilterUsername, e.target.value)} placeholder="搜索用户名" />}<select aria-label="结果" value={filterResult} onChange={e => change(setFilterResult, e.target.value)}><option value="">全部结果</option><option value="accepted">Accepted</option><option value="wa">Wrong Answer</option><option value="tle">Time Limit</option><option value="mle">Memory Limit</option><option value="re">Runtime Error</option><option value="ce">Compile Error</option><option value="pending">Pending</option><option value="judging">Judging</option></select><select aria-label="语言" value={filterLanguage} onChange={e => change(setFilterLanguage, e.target.value)}><option value="">全部语言</option>{['c','cpp','cpp14','cpp17','cpp20','java','python','python3','pascal','go','rust'].map(l => <option key={l} value={l}>{LANGUAGE_LABEL_MAP[l] || l}</option>)}</select><div className={styles.filterAction}><Button variant="secondary" onClick={resetFilters}>重置</Button></div></div>
    {error && <LoadError compact message={error} onRetry={onRetry || (() => undefined)} />}{loading && submissions.length === 0 ? <SkeletonRegion rows={6} label="评测记录正在准备" /> : <div className={styles.scroll}><table className={styles.table} style={{ opacity: loading ? .72 : 1 }}><thead><tr><th>评测 ID</th>{!hideProblemSource && <th>序号</th>}{training.isAdmin && <><th>姓名</th><th>用户名</th></>}<th>{hideOiResults ? '提交状态' : '评测结果'}</th>{scoreBased && <th className={styles.center}>分数</th>}{!hideOiResults && <><th>耗时 (MS)</th><th>内存 (MB)</th></>}<th>代码长度 (B)</th><th>语言</th><th>提交时间</th></tr></thead><tbody>
      {submissions.length === 0 ? <tr><td colSpan={training.isAdmin ? (hideProblemSource ? 10 : 11) : (hideProblemSource ? 8 : 9)} className={styles.empty}>暂无评测记录</td></tr> : submissions.map(s => <tr key={s.id}><td><button type="button" className={styles.titleButton} onClick={() => onViewSubmission(s.id)}>#{s.id}</button></td>{!hideProblemSource && <td><span className={styles.problemCode}>{s.problemOrderIndex == null ? '-' : toExcelColumnName(s.problemOrderIndex)}</span></td>}{training.isAdmin && <><td><UserIdentityLink id={s.userId} userType={s.userType} name={s.userName} username={s.username} /></td><td className={styles.muted}><UserIdentityLink id={s.userId} userType={s.userType} username={s.username} /></td></>}<td>{resultBadge(s.result, s.hidden, s.displayResult)}</td>{scoreBased && <td className={`${styles.center} ${styles.numeric}`}>{s.hidden ? '-' : s.score ?? '-'}</td>}{!hideOiResults && <><td className={styles.numeric}>{s.timeUsed ?? '-'}</td><td className={styles.numeric}>{s.memoryUsed != null ? (s.memoryUsed / 1024).toFixed(2) : '-'}</td></>}<td className={styles.numeric}>{s.codeLength ?? '-'}</td><td><button type="button" className={styles.titleButton} onClick={() => onLanguageClick(s.id)}>{LANGUAGE_LABEL_MAP[s.language] || s.language}</button></td><td className={`${styles.muted} ${styles.numeric}`}>{new Date(s.createdAt).toLocaleString('zh-CN')}</td></tr>)}
    </tbody></table></div>}
    {submissionsTotal > 50 && <div className={styles.pager}><Button variant="secondary" disabled={submissionsPage <= 1} onClick={() => setSubmissionsPage(p => p - 1)}>上一页</Button><span className={styles.muted}>{submissionsPage} / {pages}</span><Button variant="secondary" disabled={submissionsPage >= pages} onClick={() => setSubmissionsPage(p => p + 1)}>下一页</Button></div>}
  </div>
}
